# Generated by Django 2.1.5 on 2020-05-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
