# Generated by Django 2.1.5 on 2020-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200521_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularpizza',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
