# Generated by Django 2.1.5 on 2020-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.CharField(max_length=9999),
        ),
    ]
