# Generated by Django 2.1.5 on 2020-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_subextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
